#!/usr/bin/env python3
"""Embed assets/images/logo.png as a Dart constant for reliable Flutter web loading."""
from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "images" / "logo.png"
OUT = ROOT / "lib" / "generated" / "logo_base64.g.dart"


def main() -> None:
    data = SRC.read_bytes()
    b64 = base64.b64encode(data).decode("ascii")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by scripts/embed_logo_base64.py — do not edit.\n"
        "const String kEmbeddedLogoPngBase64 =\n"
        f'    "{b64}";\n',
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
